site_prefix: "/e"
shared_assets_path: "/assets"
site_title: "Kartta-Labs editor"
sign_out_path: "/oauth2/sign_out"
other_user_db_update_url: "http://localhost:3000/w/admin/api/v1/users/update.json"
other_user_db_delete_url: "http://localhost:3000/w/admin/api/v1/users/delete.json"
id_key: "xxxx"
server_url: "localhost:2900"
google_auth_id: ""
google_auth_secret: ""
google_openid_realm: "http://localhost:2900"
generator: "Kartta Labs Editor Server"
support_email: "someone@example.com"
email_from: "someone@example.com"
email_return_path: "someone@example.com"
sendgrid_api_key: ""
storage_url : "https://storage.googleapis.com"
